[build]
command = "pnpm run build"
publish = "dist"

# MCP function redirect
[[redirects]]
from = "/mcp"
to = "/.netlify/functions/mcp-server"
status = 200
force = true

[[redirects]]
from = "/mcp/*"
to = "/.netlify/functions/mcp-server"
status = 200

# Dev routes redirect
[[redirects]]
from = "/"
to = "/.netlify/functions/mcp-server"
status = 200

[[redirects]]
from = "/dev"
to = "/.netlify/functions/mcp-server"
status = 200

[[redirects]]
from = "/dev/*"
to = "/.netlify/functions/mcp-server"
status = 200

[[redirects]]
from = "/authorize"
to = "/.netlify/functions/mcp-server"
status = 200
