[build]
command = "npm run build"
publish = "out"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[dev]
command = "npm run dev"
publish = ".next"

# Next.js redirects for client-side routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# MCP function redirect
[[redirects]]
force = true
from = "/mcp"
status = 200
to = "/.netlify/functions/express-mcp-server"
