[build]
command = "npm run build"
publish = "dist"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[dev]
command = "npm run dev"
publish = "dist"

[[redirects]]
force = true
from = "/mcp"
status = 200
to = "/.netlify/functions/express-mcp-server"
